markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title.html
rdiscount:
  extensions: [smart]

name: Arjan Wulder
author: Arjan Wulder
url: http://www.wulder.nl
description: Wulder.nl is a blog which has a high focus on web and software development techniques and guides.
keywords: Java, JVM, Testing, TDD, Scrum, Continious Integration, Javascript, Web, Productivity, Blog
twitter: arjanwulder
github: awulder
linkedin: arjanwulder
gravatar: http://www.gravatar.com/avatar/fcc627acc4139764658cf3a43c987648
